name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Copy deployment scripts to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          target: ${{ secrets.SERVER_DEPLOY_PATH }}
          overwrite: true
          source: "ci/deploy.sh,ci/docker-compose.yaml"
          strip_components: 1

      - name: Execute main deployment script
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: cd ${{ secrets.SERVER_DEPLOY_PATH }} && ./deploy.sh
